openapi: 3.0.0
info:
  title: Jobs Search
  contact: {}
  version: '1.0'
servers:
- url: https://jobs-api-8280.herokuapp.com/api/v1
  variables: {}
paths:
  /jobs:
    get:
      tags:
      - Jobs
      summary: get all jobs
      operationId: getalljobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobs-api-8280.herokuapp.com/api/v1
        variables: {}
    post:
      tags:
      - Jobs
      summary: Create Job
      operationId: CreateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateJobRequest'
              - example:
                  company: Facebook
                  position: Front end developer
            example:
              company: Facebook
              position: Front end developer
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobs-api-8280.herokuapp.com/api/v1
        variables: {}
  /jobs/{id}:
    get:
      tags:
      - Jobs
      summary: Get Job
      operationId: GetJob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobs-api-8280.herokuapp.com/api/v1
        variables: {}
    patch:
      tags:
      - Jobs
      summary: update a job
      operationId: updateajob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/updateajobrequest'
              - example:
                  company: AMAZON
                  position: front end developer
                  status: interview
            example:
              company: AMAZON
              position: front end developer
              status: interview
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobs-api-8280.herokuapp.com/api/v1
        variables: {}
    delete:
      tags:
      - Jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobs-api-8280.herokuapp.com/api/v1
        variables: {}
  /auth/register:
    post:
      tags:
      - Auth
      summary: register
      operationId: register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/registerrequest'
              - example:
                  name: abc
                  email: abc@gmail.com
                  password: abc123
            example:
              name: abc
              email: abc@gmail.com
              password: abc123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://jobs-api-8280.herokuapp.com/api/v1
        variables: {}
  /auth/login:
    post:
      tags:
      - Auth
      summary: login
      operationId: login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/loginrequest'
              - example:
                  email: abc@gmail.com
                  password: abc123
            example:
              email: abc@gmail.com
              password: abc
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://jobs-api-8280.herokuapp.com/api/v1
        variables: {}
components:
  schemas:
    updateajobrequest:
      title: updateajobrequest
      required:
      - company
      - position
      - status
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        status:
          type: string
      example:
        company: AMAZON
        position: front end developer
        status: interview
    CreateJobRequest:
      title: CreateJobRequest
      required:
      - company
      - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Facebook
        position: Front end developer
    registerrequest:
      title: registerrequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: abc
        email: abc@gmail.com
        password: abc123
    loginrequest:
      title: loginrequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: abc@gmail.com
        password: abc123
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Auth
  description: ''
- name: Jobs
  description: ''
